apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: kafka-cluster
  name: redhat-user
  namespace: kafka
spec:
  authentication:
    password:
      valueFrom:
        secretKeyRef:
          key: kafka-user-password
          name: kafka-user-password
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operation: All
        resource:
          name: events
          patternType: literal
          type: topic
      - host: '*'
        operation: All
        resource:
          name: '*'
          patternType: literal
          type: group
    type: simple